### ISSUE TITLE
iOS Extensions signing?

### ISSUE THREAD

**Issue by lassana** [MicrosoftDocs/appcenter-docs#48]
Hello,
Does App Center support iOS extensions signing? As I can see, only one provisioning profile can be uploaded into the build configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d72f6fe-74d6-696e-e709-5f6d577c0a58
* Version Independent ID: b3d0ea8b-5a1f-bf71-7dc2-9685cf23c00b
* [Content](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/xamarin.md)
* Service: vs-appcenter

**Comment by dipree** [comment]
Hi, unfortunately we don't support to sign iOS extensions at the moment.

**Comment by lassana** [comment]
@derpixeldan thank you for the answer. Do you have any plans about this?

**Comment by siminapasat** [comment]
@lassana Yes, we recognize that this is a missing feature and it is on our future plans. Unfortunately, I don't have an ETA for this.

**Comment by streinhard** [comment]
+1 For this feature, this would allow us to ditch our old CI solution and switch to AppCenter completly ;)

**Comment by lassana** [comment]
Hi @siminapasat is there any update on this?

**Comment by nilofer** [comment]
Hi @lassana, we released support for iOS extensions recently! You can read more about it in our blog post: https://blogs.msdn.microsoft.com/vsappcenter/announcing-ios-app-extension-and-watchos-support-in-visual-studio-app-center/

**Comment by lassana** [comment]
Cool! Thank you for rapid response!

**Comment by lassana** [comment]
@nrajpurkar Hi,
Unfortunately, iOS app extension signing still doesn't work for us.

The docs say:

>App Center will automatically detect any watchOS or app extension targets in the project and provide fields to upload the certificate and provisioning profiles required

However, I do not observe this section in our Build configuration, only one provisioning profile can be uploaded:

![screen shot 2019-02-03 at 7 29 17 pm](https://user-images.githubusercontent.com/2004960/52179321-1c2c3300-27ea-11e9-8e46-0cb06b463d5e.png)


I've re-uploaded both `p12` and `mobileprovision` files, started a new build and, as expected, the build failed with the following error:

```
"/Users/vsts/agent/2.144.2/work/1/s/***********.sln" (Rebuild target) (1) ->
"/Users/vsts/agent/2.144.2/work/1/s/iOS/**********.iOS.csproj" (Rebuild target) (2) ->
"/Users/vsts/agent/2.144.2/work/1/s/**********.iOS.ShareExtension/**********.iOS.ShareExtension.csproj" (default target) (6) ->
  Info.plist : error : Project bundle identifier 'com.**********.shareextension' does not match specified provisioning profile 'b231c9ba-1643-49d7-9bc3-04feb86e57a5' [/Users/vsts/agent/2.144.2/work/1/s/**********.iOS.ShareExtension/**********.iOS.ShareExtension.csproj]

```

Build configuration still doesn't let me to upload additional provisioning profiles. Could you explain how AppCenter actually detects app extensions?

**Comment by nilofer** [comment]
Hi @lassana, can you get in touch with us using the blue chat bubble in the corner of the App Center portal? We'll be able to better take a look at the issue you'e seeing there. Thanks!

**Comment by lassana** [comment]
@nrajpurkar can you confirm that iOS extension signing is available for native Obj-C/Swift apps only and not for Xamarin?

**Comment by nilofer** [comment]
@lassana, that is correct and shown in our [docs](https://docs.microsoft.com/en-us/appcenter/build/xamarin/ios/#38-code-signing). We do not currently support extensions for Xamarin apps. We recently opened up a [public-facing repository](https://github.com/Microsoft/appcenter) where you can feel free to create an issue for support for this.
